---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: localhost:5001/target-01-db:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "idor_broken_authz_trading_platform"
        - name: MYSQL_DATABASE
          value: "database"
        readinessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - "-h"
              - "127.0.0.1"
              - "--password=idor_broken_authz_trading_platform"
              - "-u"
              - "root"
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: localhost:5001/target-01:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: db
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: idor_broken_authz_trading_platform
        - name: DB_NAME
          value: database
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
